[package]
name = "autograd"
version = "0.1.0"
authors = ["bokutotu <mushin.hudoushin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version="0.15.1"}
num-traits = "0.2.14"
num = "0.3"
